/*
Copyright (c) 2021 The UNSAT Group. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Luke Nelson, Xi Wang
*/

/* A large (but trivial) program with 40 instructions. */

r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2
r1 = r2

exit
