image: unsat/lean:3.35.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BOOLECTOR: /opt/boolector/3.2.1-cadical/bin/boolector
  Z3: /opt/z3/4.8.7/bin/z3

before_script:
  - cd lean && leanpkg configure

stages:
  - build
  - test

build-lean:
  stage: build
  script:
    - leanpkg build
  artifacts:
    paths:
      - lean/_target/
      - lean/src/**/*.olean
    expire_in: 1 hr

build-bpf:
  stage: build
  script:
    - make -B bpf-examples
  artifacts:
    paths:
      - lean/test/bpf/examples/*.bin
      - lean/test/bpf/examples/absint/*.bin
      - lean/test/bpf/examples/symeval/*.bin
      - lean/test/bpf/examples/common/*.bin
    expire_in: 1 hr

generate-proofs:
  script:
    - leanpkg build && make -j8 proofs

test-lean:
  script:
    - leanpkg build && leanpkg test -- --tstack=32000

test-python-tests:
  script:
    - green -vv -f test

test-racket:
  script:
    - raco test -- ../racket/test
