/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_main_window (void);
GtkWidget *create_filechooserdialog_open (void);
GtkWidget *create_filechooserdialog_save (void);
GtkWidget *create_fontselectiondialog (void);
GtkWidget *create_quitdialog (void);
GtkWidget *create_gotodialog (void);
