language: cpp
compiler:
  - gcc
os: linux
dist: xenial
jobs:
  include:
    - name: python 2.7
      env: PYTHON=python2
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install python python-pip python-setuptools python-wheel
      after_success:
        - coveralls --gcov-options '\-lp' -i $PWD/vm/ubpf_vm.c -i $PWD/vm/ubpf_jit_x86_64.c -i $PWD/vm/ubpf_loader.c
    - name: python 3.5
      env: PYTHON=python3
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel
# command to install dependencies
install:
  - $PYTHON -m pip install --upgrade "pip<21.0"
  - $PYTHON -m pip install -r requirements.txt
  - $PYTHON -m pip install cpp-coveralls
# command to run tests
script: 
  - make -C vm COVERAGE=1
  - nosetests -v
