
MAKEFLAGS += --no-builtin-rules

LLVM_CONFIG     := llvm-config
ifeq ($(shell which $(LLVM_CONFIG) 2> /dev/null),)
LLVM_CONFIG     := /usr/local/opt/llvm/bin/llvm-config
endif
ifeq ($(shell which $(LLVM_CONFIG) 2> /dev/null),)
LLVM_CONFIG     := /opt/homebrew/opt/llvm/bin/llvm-config
endif
ifeq ($(shell which $(LLVM_CONFIG) 2> /dev/null),)
LLVM_PREFIX     :=
else
LLVM_PREFIX     := "$(shell $(LLVM_CONFIG) --bindir)/"
endif

LLVM_CC           := $(LLVM_PREFIX)clang
LLVM_CLANG_FORMAT := $(LLVM_PREFIX)clang-format
LLVM_LD           := $(LLVM_PREFIX)ld.lld
LLVM_LINK         := $(LLVM_PREFIX)llvm-link
LLVM_MC           := $(LLVM_PREFIX)llvm-mc
LLVM_OBJCOPY      := $(LLVM_PREFIX)llvm-objcopy
LLVM_OBJDUMP      := $(LLVM_PREFIX)llvm-objdump
LLVM_OPT          := $(LLVM_PREFIX)opt

V               = @
Q               = $(V:1=)
QUIET_GEN       = $(Q:@=@echo    '     GEN      '$@;)
QUIET_CC        = $(Q:@=@echo    '     CC       '$@;)

rwildcard       = $(foreach d,$(wildcard $1*),$(call rwildcard,$d/,$2) $(filter $(subst *,%,$2),$d))
